name: Add new issues to the NFT-barter project

on:
  issues:
    types:
      - opened

jobs:
  issue-automation:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: NFT-barter
          column: Todo
          repo-token: ${{ secrets.GHPROJECT_TOKEN }}
