name: Build and run tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      VESSEL_VERSION: 0.6.3
      DFX_VERSION: 0.9.3
      WASMTIME_VERSION: 0.37.0
      NODE_VERSION: 16
      NFT_BARTER_DIR: nft-barter
      GENERATIVE_ART_NFT_DIR: generative-art-nft

    steps:
      # Setups
      - name: Checkout nft-barter
        uses: actions/checkout@v3
        with:
          path: ${{ env.NFT_BARTER_DIR }}
      - name: Checkout generative-art-nft
        uses: actions/checkout@v3
        with:
          repository: Japan-DfinityInfoHub/generative-art-nft
          path: ${{ env.GENERATIVE_ART_NFT_DIR }}
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm install -g npm
      - name: Install dfx/moc/vessel
        uses:  aviate-labs/setup-dfx@v0.2.3
        with:
          dfx-version: ${{ env.DFX_VERSION }}
          install-moc: true
          vessel-version: ${{ env.VESSEL_VERSION }}
      - name: Install wasmtime
        uses: mwilliamson/setup-wasmtime-action@v1
        with:
          wasmtime-version: ${{ env.WASMTIME_VERSION }}
      - name: Show versions
        run: |
          dfx --version
          moc --version
          vessel --version
          wasmtime --version

      # Motoko tests
      - name: Motoko type checking
        working-directory: ${{ env.NFT_BARTER_DIR }}
        run: ./scripts/motoko_type_check.sh
      - name: Motoko unit tests
        working-directory: ${{ env.NFT_BARTER_DIR }}
        run: ./scripts/motoko_tests.sh

      # e2e tests
      - name: Start the local replica
        working-directory: ${{ env.NFT_BARTER_DIR }}
        run: dfx start --background
      - name: Setup generative-art-nft
        working-directory: ${{ env.GENERATIVE_ART_NFT_DIR }}
        run: |
          npm i
          ./scripts/install_local.sh
          echo "GENERATIVE_ART_NFT_ID=$(dfx canister id GenerativeArtNFT)" >> $GITHUB_ENV
      - name: Setup nft-barter
        working-directory: ${{ env.NFT_BARTER_DIR }}
        run: |
          echo "LOCAL_NFT_CANISTER_ID=${{ env.GENERATIVE_ART_NFT_ID }}" >> .env
          npm i
          ./scripts/install_local.sh
          ./scripts/update_nft_canister_id.sh ${{ env.GENERATIVE_ART_NFT_ID }}
      - name: Run e2e tests
        working-directory: ${{ env.NFT_BARTER_DIR }}
        run: |
          npm run test
      - name: Stop dfx
        working-directory: ${{ env.NFT_BARTER_DIR }}
        run: |
          dfx stop
